# Site wide configuration

url: http://localhost:4000


# Site owner
url: http://localhost:4000
disqus-shortname: akasralikar-dev

owner:
  google:
    ad-client: ""
    ad-slot: ""
    analytics: ""
    verify: ""
  bing:
    verify: ""
  alexa:
    verify: ""
  yandex:
    verify: ""
disqus-shortname: mmistakes-dev


# Plugin: jekyll-assets

assets:
  cache: false
